pipeline {
    agent {
        node {
            label 'terraformhost'
        }
    }
	environment {
        TF_VAR_aws_access_key    = credentials('jenkins-aws-access-key')
        TF_VAR_aws_secret_key    = credentials('jenkins-aws-secret-key')
    }
    stages {
        stage('Download Terraform Code From Github') { 
            steps {
                git branch: 'master', credentialsId: 'jenkins-github-credential', url: 'https://github.com/rajakumarguptatechie/terraform.git'
            }    
        }
        stage('Run Terraform Manifest') {
            steps {
                sh """
                    cd terraform-training-synechron/tfExample01
                    terraform init -reconfigure
                    terraform plan -out=plan${BUILD_NUMBER}
                    terraform apply plan${BUILD_NUMBER}
                """    
            }
        }
    }      
}
